version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - eslint
          - '@eslint/*'
          - eslint-*
          - typescript-eslint
      swc:
        patterns:
          - '@swc/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
